<?php

/**
 * @file
 * Contains pushover.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function pushover_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the pushover module.
    case 'help.page.pushover':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Pushover integration') . '</p>';
      return $output;

    default:
  }
}
